typography_spectrum: 0.72574
color:
  brandColors:
    - '#d7deef'
    - '#030208'
    - '#272b2c'
    - '#916a63'
    - '#8e95a7'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.38143
analytics:
  google: null
  facebook: null
  twitter: null
name: whiteheart
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: the white heart
purpose: []
