name: whiteheart
favicon: null
layout_spectrum: 0.38143
typography_spectrum: 0.72574
title: website of the white heart
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7deef'
    - '#030208'
    - '#272b2c'
    - '#916a63'
    - '#8e95a7'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
