name: whiteheart
favicon: null
layout_spectrum: 0.3288114811293781
typography_spectrum: 0.18643024377524853
title: website of the white heart
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.48269296111539006
  lightness: 0.08689953456632793
  saturation: 0.036424999590963125
  rhythmicContrast: 0.5767673219088465
purpose: []
